# Generated by Django 4.2.1 on 2023-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadExperience',
            fields=[
                ('cadexperience_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cadexperience_first_name', models.CharField(max_length=50)),
                ('cadexperience_last_name', models.CharField(max_length=50)),
                ('cadexperience_degree', models.CharField(max_length=2)),
            ],
        ),
    ]
